<?php
if ( function_exists( 'register_field_group' ) ) {
	register_field_group( array(
		'id' => 'acf_stock-clients',
		'title' => 'Stock Clients',
		'fields' => array (
			array (
				'key' => 'field_5d26108ca1793',
				'label' => 'client',
				'name' => 'client',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5d60759175f5e',
						'label' => 'Código',
						'name' => 'code',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5d26111318e33',
						'label' => 'nome',
						'name' => 'name',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5d26111c2f95f',
						'label' => 'email',
						'name' => 'email',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5d261097a1794',
						'label' => 'Descontos',
						'name' => 'discounts',
						'type' => 'repeater',
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5d2610a1a1795',
								'label' => 'Letra',
								'name' => 'character',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'a' => 'a',
									'b' => 'b',
									'c' => 'c',
									'd' => 'd',
									'e' => 'e',
									'f' => 'f',
									'g' => 'g',
									'h' => 'h',
									'i' => 'i',
									'j' => 'j',
									'k' => 'k',
									'l' => 'l',
									'm' => 'm',
									'n' => 'n',
									'o' => 'o',
									'p' => 'p',
									'q' => 'q',
									'r' => 'r',
									's' => 's',
									't' => 't',
									'u' => 'u',
									'v' => 'v',
									'w' => 'w',
									'x' => 'x',
									'y' => 'y',
									'z' => 'z',
								),
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_5d2610bca1796',
								'label' => 'Desconto',
								'name' => 'discount',
								'type' => 'number',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
						),
						'row_min' => 0,
						'row_limit' => '',
						'layout' => 'table',
						'button_label' => 'Adicionar Desconto',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Adicionar cliente',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
